version: 1.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: IrXJmW9GC83p0k/2pkwEcUs2XJCfnsKERCux75emqy7oFeOo8zinFAo1wLPdTVOs
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: src/NHibernate.Json.sln
  publish_nuget: true
  verbosity: minimal
after_test:
  - cmd: coverage.bat

	
	
	

