version: 1.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: IrXJmW9GC83p0k/2pkwEcUs2XJCfnsKERCux75emqy7oFeOo8zinFAo1wLPdTVOs
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    (New-Object Net.WebClient).DownloadFile('https://www.nuget.org/nuget.exe', 'C:\projects\nhibernate-json\src\.nuget\NuGet.exe')

    nuget restore src\NHibernate.Json.sln
build:
  project: src/NHibernate.Json.sln
  publish_nuget: true
  verbosity: minimal
after_test:
  - cmd: coverage.bat
deploy:
  provider: NuGet
  api_key:
    secure: dGTD6kR4wKG1QjqgVVaLPS2EBSHvdSV8MR6+EfwWkTwkSGR8XunGqFKQjztADax1
  skip_symbols: true
  artifact: /.*\.nupkg/