on: ["push", "pull_request"]

name: Run Tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['9.0']
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - id: test
      run: |
        cd src
        dotnet test --collect:"XPlat Code Coverage" -r output
        echo "::set-output name=COVERAGE_FILE::$(find output -name '*.xml')"
