on: [push, pull_request]

name: Run Tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x.x'

      - name: Restore dependencies
        run: dotnet restore src/NHibernate.Json.Tests/NHibernate.Json.Tests.csproj

      - name: Build the project
        run: dotnet build src/NHibernate.Json.Tests/NHibernate.Json.Tests.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/NHibernate.Json.Tests/NHibernate.Json.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=tests.trx" --results-directory TestResults

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
          if-no-files-found: warn

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: .NET Tests
          path: TestResults/*.trx
          reporter: dotnet-trx
          fail-on-error: false

